### ISSUE TITLE
Angular appears before jQuery

### ISSUE THREAD

**Issue by jboothe** [klei/gulp-angular-filesort#31] opened 2015-07-20 21:43 UTC
When running angularFileSort() v1.1.1, Angular gets placed before jQuery which causes Angular to use jQLite instead of full version of jQuery. Any work-arounds?

**Comment by simon04** [comment] 2015-08-07 13:47
Seems to be a duplicate of #8 (see https://github.com/klei/gulp-angular-filesort/issues/8#issuecomment-51621195 for correct usage recommendation).

**Closed** 2016-03-23 09:52 UTC
